services:
  # postgres-user:
  #   image: postgres:15
  #   container_name: eventiq-postgres-user
  #   environment:
  #     POSTGRES_DB: eventiq_user
  #     POSTGRES_USER: eventiq
  #     POSTGRES_PASSWORD: eventiq123
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-user-data:/var/lib/postgresql/data
  #   networks:
  #     - eventiq-net

  # postgres-org:
  #   image: postgres:15
  #   container_name: eventiq-postgres-org
  #   environment:
  #     POSTGRES_DB: eventiq_org
  #     POSTGRES_USER: eventiq
  #     POSTGRES_PASSWORD: eventiq123
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - postgres-org-data:/var/lib/postgresql/data
  #   networks:
  #     - eventiq-net

  # postgres-event:
  #   image: postgres:15
  #   container_name: eventiq-postgres-event
  #   environment:
  #     POSTGRES_DB: eventiq_event
  #     POSTGRES_USER: eventiq
  #     POSTGRES_PASSWORD: eventiq123
  #   ports:
  #     - "5434:5432"
  #   volumes:
  #     - postgres-event-data:/var/lib/postgresql/data
  #   networks:
  #     - eventiq-net

  user-service:
    image: user-service
    build:
      context: .
      dockerfile: Eventiq.UserService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8081
      ConnectionStrings__Postgres: "Host=ep-twilight-meadow-a1idagy9-pooler.ap-southeast-1.aws.neon.tech;Database=neondb;Username=neondb_owner;Password=xxx;SSL Mode=Require;Search Path=user_service"
    # depends_on:
    #   postgres-user:
    #     condition: service_started
      # rabbitmq:
      #   condition: service_healthy
    volumes:
      - ./keys:/app/keys:ro
    networks:
      - eventiq-net
  org-service:
      image: org-service
      build:
        context: .
        dockerfile: Eventiq.OrganizationService/Dockerfile
      environment:
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_URLS: http://+:8082
        ConnectionStrings__Postgres: "Host=ep-twilight-meadow-a1idagy9-pooler.ap-southeast-1.aws.neon.tech;Database=neondb;Username=neondb_owner;Password=xxx;SSL Mode=Require;Search Path=org_service"
      # depends_on:
      #   postgres-org:
      #     condition: service_started
        # rabbitmq:
        #   condition: service_healthy
      volumes:
        - ./keys:/app/keys:ro
      networks:
        - eventiq-net

  event-service:
    image: event-service
    build:
      context: .
      dockerfile: Eventiq.EventService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8083
      ConnectionStrings__Postgres: "Host=ep-twilight-meadow-a1idagy9-pooler.ap-southeast-1.aws.neon.tech;Database=neondb;Username=neondb_owner;Password=xxx;SSL Mode=Require;Search Path=event_service"
    # depends_on:
    #   postgres-event:
    #     condition: service_started
      # rabbitmq:
      #   condition: service_healthy
    volumes:
      - ./keys:/app/keys:ro
    networks:
      - eventiq-net

  api-gateway:
    image: api-gateway
    build:
      context: .
      dockerfile: Eventiq.ApiGateway/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - user-service
      - org-service
      - event-service
      - seat-service
    ports:
      - "5001:8080"
    volumes:
      - ./keys:/app/keys:ro
    networks:
      - eventiq-net

  email-service:
    image: email-service
    build:
      context: .
      dockerfile: Eventiq.EmailService/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: Development
      ASPNETCORE_ENVIRONMENT: Development
      RabbitMq__ConnectionString: amqps://zbiaqafr:yegz8imBRoFKi47FjaY7JW4g2UZ0bMaX@gerbil.rmq.cloudamqp.com/zbiaqafr
    # depends_on:
    #   rabbitmq:
    #     condition: service_healthy
    networks:
      - eventiq-net

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: eventiq
  #     RABBITMQ_DEFAULT_PASS: eventiq123
  #   healthcheck:
  #     test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   networks:
  #     - eventiq-net
  contracts:
    image:  contracts
    build:
      context: .
      dockerfile: Eventiq.Contracts/Dockerfile

  # postgres-seat:
  #   image: postgres:15
  #   container_name: eventiq-postgres-seat
  #   environment:
  #     POSTGRES_DB: eventiq_seat
  #     POSTGRES_USER: eventiq
  #     POSTGRES_PASSWORD: eventiq123
  #   ports:
  #     - "5435:5432"
  #   volumes:
  #     - postgres-seat-data:/var/lib/postgresql/data
  #   networks:
  #     - eventiq-net

  # redis:
  #   image: redis:7-alpine
  #   container_name: eventiq-redis
  #   ports:
  #     - "6379:6379"
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - eventiq-net

  seat-service:
    image: seat-service
    build:
      context: .
      dockerfile: Eventiq.SeatService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8084
      ConnectionStrings__Postgres: "Host=ep-twilight-meadow-a1idagy9-pooler.ap-southeast-1.aws.neon.tech;Database=neondb;Username=neondb_owner;Password=xxx;SSL Mode=Require;Search Path=seat_service"
      ConnectionStrings__Redis: "easy-tahr-80535.upstash.io:6379,password=xxx,ssl=True,abortConnect=False"
    # depends_on:
    #   postgres-seat:
    #     condition: service_started
      # redis:
      #   condition: service_started
      # rabbitmq:
      #   condition: service_healthy
    volumes:
      - ./keys:/app/keys:ro
    networks:
      - eventiq-net

#volumes:
  # postgres-user-data:
  # postgres-org-data:
  # postgres-event-data:
  # postgres-seat-data:
  # redis-data:

networks:
  eventiq-net:
    driver: bridge

