"""DDL cache for ~25 business tables across the 5 service schemas.

AUTO-GENERATED by scripts/refresh_schema_dump.py — do not edit by hand.
Re-run the script after migrations. Manual notes live in the script's
`ANNOTATIONS` dict.

Excluded by design (see system_tables.py): MassTransit + EF metadata.
"""
from __future__ import annotations

# Each value is a CREATE TABLE-style block. The prompt builder loads
# the DDL of relevant tables and pastes them verbatim into the LLM
# prompt context.

SCHEMA: dict[str, str] = {
    'event_service.charts': """\
CREATE TABLE event_service.charts (
  id          uuid         PRIMARY KEY,
  name        text         NOT NULL,
  event_id    uuid         NOT NULL,
  created_at  timestamptz  NOT NULL,
  updated_at  timestamptz,
  deleted_at  timestamptz,
  is_deleted  bool         NOT NULL
);""",
    'event_service.events': """\
CREATE TABLE event_service.events (
  id                  uuid         PRIMARY KEY,
  organization_id     uuid         NOT NULL,
  organization_name   text         NOT NULL,  -- snapshot
  oranization_avatar  text,  -- SIC: typo in code, keep as-is
  event_banner        text,
  name                text         NOT NULL,
  description         text,
  detail_address      text,
  province_code       text,
  commune_code        text,
  province_name       text,
  commune_name        text,
  status              int          NOT NULL,  -- 0=Draft 1=Pending 2=Approved 3=Rejected 4=Published 5=Cancelled
  start_time          timestamptz,
  end_time            timestamptz,
  created_at          timestamptz  NOT NULL,
  updated_at          timestamptz,
  deleted_at          timestamptz,
  is_deleted          bool         NOT NULL  -- soft delete flag
);""",
    'event_service.legends': """\
CREATE TABLE event_service.legends (
  id          uuid         PRIMARY KEY,
  name        text         NOT NULL,
  color       text,
  price       int          NOT NULL,  -- integer (NOT numeric) — careful when SUM with orders.total_amount
  event_id    uuid         NOT NULL,
  created_at  timestamptz  NOT NULL,
  updated_at  timestamptz,
  deleted_at  timestamptz,
  is_deleted  bool         NOT NULL
);""",
    'event_service.org_payment_info': """\
CREATE TABLE event_service.org_payment_info (
  organization_id    uuid         PRIMARY KEY,  -- logical FK -> org_service."Organizations"."Id"
  stripe_account_id  text         NOT NULL,
  is_active          bool         NOT NULL,
  updated_at         timestamptz  NOT NULL
);""",
    'event_service.sessions': """\
CREATE TABLE event_service.sessions (
  id          uuid         PRIMARY KEY,
  name        text         NOT NULL,
  start_time  timestamptz  NOT NULL,
  end_time    timestamptz  NOT NULL,
  event_id    uuid         NOT NULL,
  chart_id    uuid         NOT NULL,
  created_at  timestamptz  NOT NULL,
  updated_at  timestamptz,
  deleted_at  timestamptz,
  is_deleted  bool         NOT NULL
);""",
    'event_service.submissions': """\
CREATE TABLE event_service.submissions (
  id           uuid         PRIMARY KEY,
  event_id     uuid         NOT NULL,
  admin_email  text         NOT NULL,
  admin_id     uuid         NOT NULL,
  message      text         NOT NULL,
  status       int          NOT NULL,  -- integer enum: 0=Pending 1=Approved 2=Rejected 3=Withdrawn
  created_at   timestamptz  NOT NULL,
  updated_at   timestamptz,
  deleted_at   timestamptz,
  is_deleted   bool         NOT NULL
);""",
    'event_service.tickets': """\
CREATE TABLE event_service.tickets (
  id             uuid           PRIMARY KEY,
  order_id       uuid           NOT NULL,  -- logical FK -> payment_service.orders.id
  session_id     uuid           NOT NULL,
  seat_id        uuid           NOT NULL,  -- logical FK -> seat_service.seats.id
  seat_label     text           NOT NULL,
  legend_name    text           NOT NULL,
  price          numeric(18,2)  NOT NULL,
  qr_code        text           NOT NULL,
  is_checked_in  bool           NOT NULL,
  checked_in_at  timestamptz,
  issued_at      timestamptz    NOT NULL,
  created_at     timestamptz    NOT NULL,
  updated_at     timestamptz,
  deleted_at     timestamptz,
  is_deleted     bool           NOT NULL
);""",
    'org_service."Invitations"': """\
CREATE TABLE org_service."Invitations" (
  "Id"              uuid         PRIMARY KEY,
  "OrganizationId"  uuid         NOT NULL,
  "UserId"          uuid,
  "UserEmail"       text         NOT NULL,
  "ExpiresAt"       timestamptz  NOT NULL,
  "Status"          int          NOT NULL,  -- integer enum: 0=Pending 1=Accepted 2=Rejected 3=Expired
  "PermissionId"    uuid         NOT NULL,
  "CreatedAt"       timestamptz  NOT NULL,
  "UpdatedAt"       timestamptz,
  "DeletedAt"       timestamptz,
  "IsDeleted"       bool         NOT NULL
);""",
    'org_service."Members"': """\
CREATE TABLE org_service."Members" (
  "Id"              uuid         PRIMARY KEY,
  "UserId"          uuid,
  "Email"           text         NOT NULL,
  "OrganizationId"  uuid         NOT NULL,
  "PermissionId"    uuid         NOT NULL,
  "CreatedAt"       timestamptz  NOT NULL,
  "UpdatedAt"       timestamptz,
  "DeletedAt"       timestamptz,
  "IsDeleted"       bool         NOT NULL
);""",
    'org_service."Organizations"': """\
CREATE TABLE org_service."Organizations" (
  "Id"                   uuid         PRIMARY KEY,
  "Name"                 text         NOT NULL,
  "Description"          text,
  "OwnerId"              uuid         NOT NULL,
  "OwnerEmail"           text         NOT NULL,
  "StripeAccountId"      text,
  "PaymentStatus"        int          NOT NULL,  -- integer enum: 0=NotConfigured 1=Pending 2=Active 3=Restricted
  "PaymentConfiguredAt"  timestamptz,
  "CreatedAt"            timestamptz  NOT NULL,
  "UpdatedAt"            timestamptz,
  "DeletedAt"            timestamptz,
  "IsDeleted"            bool         NOT NULL
);""",
    'org_service."PayoutLogs"': """\
CREATE TABLE org_service."PayoutLogs" (
  "Id"              uuid         PRIMARY KEY,
  "OrgId"           uuid         NOT NULL,
  "StripePayoutId"  text         NOT NULL,
  "Amount"          bigint       NOT NULL,
  "Currency"        text         NOT NULL,
  "TriggeredAt"     timestamptz  NOT NULL
);""",
    'org_service."Permissions"': """\
CREATE TABLE org_service."Permissions" (
  "Id"              uuid         PRIMARY KEY,
  "Name"            text         NOT NULL,
  "OrganizationId"  uuid         NOT NULL,
  "IsDesigner"      bool         NOT NULL,
  "CreatedAt"       timestamptz  NOT NULL,
  "UpdatedAt"       timestamptz,
  "DeletedAt"       timestamptz,
  "IsDeleted"       bool         NOT NULL
);""",
    'org_service."PlatformConfigs"': """\
CREATE TABLE org_service."PlatformConfigs" (
  "Id"                int           PRIMARY KEY,
  "CurrentFeeRate"    numeric(5,4)  NOT NULL,
  "PendingFeeRate"    numeric(5,4),
  "EffectiveDate"     timestamptz,
  "PayoutDayOfMonth"  int           NOT NULL,
  "UpdatedAt"         timestamptz,
  "UpdatedBy"         uuid
);""",
    'payment_service.order_items': """\
CREATE TABLE payment_service.order_items (
  id           uuid           PRIMARY KEY,
  order_id     uuid           NOT NULL,
  seat_id      uuid           NOT NULL,  -- logical FK -> seat_service.seats.id
  seat_label   text           NOT NULL,
  legend_name  text           NOT NULL,
  price        numeric(18,2)  NOT NULL,
  created_at   timestamptz    NOT NULL,
  updated_at   timestamptz,
  deleted_at   timestamptz,
  is_deleted   bool           NOT NULL
);""",
    'payment_service.orders': """\
CREATE TABLE payment_service.orders (
  id                 uuid           PRIMARY KEY,
  user_id            uuid           NOT NULL,  -- logical FK -> user_service."Users"."Id"
  org_id             uuid           NOT NULL,  -- logical FK -> org_service."Organizations"."Id"
  session_id         uuid           NOT NULL,  -- logical FK -> event_service.sessions.id
  stripe_session_id  text           NOT NULL,
  status             text           NOT NULL,  -- text enum: 'Pending' | 'Paid' | 'Failed' | 'Refunded'
  total_amount       numeric(18,2)  NOT NULL,
  platform_fee       numeric(18,2)  NOT NULL,
  event_name         text           NOT NULL,  -- snapshot
  session_name       text           NOT NULL,  -- snapshot
  session_date       timestamptz    NOT NULL,  -- snapshot
  paid_at            timestamptz,
  created_at         timestamptz    NOT NULL,
  updated_at         timestamptz,
  deleted_at         timestamptz,
  is_deleted         bool           NOT NULL
);""",
    'seat_service.objects': """\
CREATE TABLE seat_service.objects (
  id           uuid         PRIMARY KEY,
  seat_map_id  uuid         NOT NULL,
  object_type  text         NOT NULL,
  label        text,
  geometry     jsonb,
  style        jsonb,
  z_index      int          NOT NULL,
  created_at   timestamptz  NOT NULL,
  updated_at   timestamptz,
  deleted_at   timestamptz,
  is_deleted   bool         NOT NULL
);""",
    'seat_service.seat_maps': """\
CREATE TABLE seat_service.seat_maps (
  id               uuid         PRIMARY KEY,
  chart_id         uuid         NOT NULL,
  event_id         uuid         NOT NULL,
  organization_id  uuid         NOT NULL,
  name             text         NOT NULL,
  status           text         NOT NULL,  -- text enum: 'Draft' | 'Published' | 'Archived'
  canvas_settings  jsonb,
  version          int          NOT NULL,
  created_at       timestamptz  NOT NULL,
  updated_at       timestamptz,
  deleted_at       timestamptz,
  is_deleted       bool         NOT NULL,
  session_id       uuid,  -- NULL=template, NOT NULL=per-session clone
  total_seats      int          NOT NULL
);""",
    'seat_service.seats': """\
CREATE TABLE seat_service.seats (
  id                 uuid         PRIMARY KEY,
  label              text         NOT NULL,
  seat_number        int          NOT NULL,
  status             text         NOT NULL,  -- text enum: 'Available' | 'Holding' | 'Sold' | 'Blocked'
  seat_type          int          NOT NULL,  -- 1..4
  position           jsonb,
  legend_id          uuid,  -- logical FK -> event_service.legends.id
  custom_properties  jsonb,
  created_at         timestamptz  NOT NULL,
  updated_at         timestamptz,
  deleted_at         timestamptz,
  is_deleted         bool         NOT NULL,
  held_by            uuid,
  held_until         timestamptz,
  seat_map_id        uuid         NOT NULL
);""",
    'seat_service.versions': """\
CREATE TABLE seat_service.versions (
  id                  uuid         PRIMARY KEY,
  seat_map_id         uuid         NOT NULL,
  version_number      int          NOT NULL,
  snapshot            jsonb        NOT NULL,
  created_by          uuid         NOT NULL,
  change_description  text,
  created_at          timestamptz  NOT NULL,
  updated_at          timestamptz,
  deleted_at          timestamptz,
  is_deleted          bool         NOT NULL
);""",
    'user_service."BanHistories"': """\
CREATE TABLE user_service."BanHistories" (
  "Id"          uuid         PRIMARY KEY,
  "UserId"      uuid         NOT NULL,
  "Reason"      text,
  "BannedById"  uuid         NOT NULL,
  "CreatedAt"   timestamptz  NOT NULL,
  "UpdatedAt"   timestamptz,
  "DeletedAt"   timestamptz,
  "IsDeleted"   bool         NOT NULL
);""",
    'user_service."PasswordResetTokens"': """\
CREATE TABLE user_service."PasswordResetTokens" (
  "Id"         uuid         PRIMARY KEY,
  "Token"      text         NOT NULL,
  "Expires"    timestamptz  NOT NULL,
  "UserId"     uuid         NOT NULL,
  "CreatedAt"  timestamptz  NOT NULL,
  "UpdatedAt"  timestamptz,
  "DeletedAt"  timestamptz,
  "IsDeleted"  bool         NOT NULL
);""",
    'user_service."RefreshTokens"': """\
CREATE TABLE user_service."RefreshTokens" (
  "Id"              uuid         PRIMARY KEY,
  "Token"           text         NOT NULL,
  "Expires"         timestamptz  NOT NULL,
  "UserId"          uuid         NOT NULL,
  "CreatedAt"       timestamptz  NOT NULL,
  "UpdatedAt"       timestamptz,
  "DeletedAt"       timestamptz,
  "IsDeleted"       bool         NOT NULL,
  "OrganizationId"  uuid,
  "OrgName"         text
);""",
    'user_service."Roles"': """\
CREATE TABLE user_service."Roles" (
  "Id"         uuid         PRIMARY KEY,
  "Name"       text         NOT NULL,  -- 'Admin' | 'User' | 'Staff' | 'Organization'
  "CreatedAt"  timestamptz  NOT NULL,
  "UpdatedAt"  timestamptz,
  "DeletedAt"  timestamptz,
  "IsDeleted"  bool         NOT NULL
);""",
    'user_service."UserRoles"': """\
CREATE TABLE user_service."UserRoles" (
  "UserId"          uuid         NOT NULL,
  "RoleId"          uuid         NOT NULL,
  "OrganizationId"  uuid,  -- nullable — cross-org role assignment
  "Id"              uuid         PRIMARY KEY,
  "CreatedAt"       timestamptz  NOT NULL,
  "UpdatedAt"       timestamptz,
  "DeletedAt"       timestamptz,
  "IsDeleted"       bool         NOT NULL
);""",
    'user_service."Users"': """\
CREATE TABLE user_service."Users" (
  "Id"            uuid         PRIMARY KEY,
  "Email"         text         NOT NULL,
  "Username"      text         NOT NULL,
  "IsBanned"      bool         NOT NULL,
  "PasswordHash"  text         NOT NULL,
  "Avatar"        text         NOT NULL,
  "CreatedAt"     timestamptz  NOT NULL,
  "UpdatedAt"     timestamptz,
  "DeletedAt"     timestamptz,
  "IsDeleted"     bool         NOT NULL  -- soft delete flag
);""",
}


def get_ddl(table_fq: str) -> str:
    return SCHEMA[table_fq]


def all_tables() -> list[str]:
    return list(SCHEMA.keys())
