// <auto-generated />
using System;
using Eventiq.SeatService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Eventiq.SeatService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SeatDbContext))]
    [Migration("20260624090125_AddNextSeatNumber")]
    partial class AddNextSeatNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("seat_service")
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Eventiq.SeatService.Domain.Entity.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomProperties")
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_properties");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("HeldBy")
                        .HasColumnType("uuid")
                        .HasColumnName("held_by");

                    b.Property<DateTime?>("HeldUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("held_until");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid?>("LegendId")
                        .HasColumnType("uuid")
                        .HasColumnName("legend_id");

                    b.Property<string>("Position")
                        .HasColumnType("jsonb")
                        .HasColumnName("position");

                    b.Property<double?>("PositionX")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("double precision")
                        .HasColumnName("position_x")
                        .HasComputedColumnSql("((position ->> 'x'))::double precision", true);

                    b.Property<double?>("PositionY")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("double precision")
                        .HasColumnName("position_y")
                        .HasComputedColumnSql("((position ->> 'y'))::double precision", true);

                    b.Property<Guid>("SeatMapId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_map_id");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("integer")
                        .HasColumnName("seat_number");

                    b.Property<int>("SeatType")
                        .HasColumnType("integer")
                        .HasColumnName("seat_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_seats");

                    b.HasIndex("SeatMapId", "Label")
                        .IsUnique()
                        .HasDatabaseName("ix_seats_seat_map_id_label")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("SeatMapId", "PositionX", "PositionY")
                        .HasDatabaseName("ix_seats_map_position")
                        .HasFilter("is_deleted = false");

                    b.ToTable("seats", "seat_service");
                });

            modelBuilder.Entity("Eventiq.SeatService.Domain.Entity.SeatMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanvasSettings")
                        .HasColumnType("jsonb")
                        .HasColumnName("canvas_settings");

                    b.Property<Guid>("ChartId")
                        .HasColumnType("uuid")
                        .HasColumnName("chart_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("NextSeatNumber")
                        .HasColumnType("integer")
                        .HasColumnName("next_seat_number");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer")
                        .HasColumnName("total_seats");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_seat_maps");

                    b.HasIndex("ChartId")
                        .IsUnique()
                        .HasDatabaseName("ix_seat_maps_chart_id_template")
                        .HasFilter("session_id IS NULL");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_seat_maps_event_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_seat_maps_organization_id");

                    b.HasIndex("ChartId", "SessionId")
                        .IsUnique()
                        .HasDatabaseName("ix_seat_maps_chart_session")
                        .HasFilter("session_id IS NOT NULL");

                    b.ToTable("seat_maps", "seat_service");
                });

            modelBuilder.Entity("Eventiq.SeatService.Domain.Entity.SeatMapVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeDescription")
                        .HasColumnType("text")
                        .HasColumnName("change_description");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("SeatMapId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_map_id");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_versions");

                    b.HasIndex("SeatMapId")
                        .HasDatabaseName("ix_versions_seat_map_id");

                    b.ToTable("versions", "seat_service");
                });

            modelBuilder.Entity("Eventiq.SeatService.Domain.Entity.SeatObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Geometry")
                        .HasColumnType("jsonb")
                        .HasColumnName("geometry");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_type");

                    b.Property<Guid>("SeatMapId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_map_id");

                    b.Property<string>("Style")
                        .HasColumnType("jsonb")
                        .HasColumnName("style");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("ZIndex")
                        .HasColumnType("integer")
                        .HasColumnName("z_index");

                    b.HasKey("Id")
                        .HasName("pk_objects");

                    b.HasIndex("SeatMapId")
                        .HasDatabaseName("ix_objects_seat_map_id");

                    b.ToTable("objects", "seat_service");
                });

            modelBuilder.Entity("Eventiq.SeatService.Domain.Entity.Seat", b =>
                {
                    b.HasOne("Eventiq.SeatService.Domain.Entity.SeatMap", "SeatMap")
                        .WithMany("Seats")
                        .HasForeignKey("SeatMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seats_seat_maps_seat_map_id");

                    b.Navigation("SeatMap");
                });

            modelBuilder.Entity("Eventiq.SeatService.Domain.Entity.SeatMapVersion", b =>
                {
                    b.HasOne("Eventiq.SeatService.Domain.Entity.SeatMap", "SeatMap")
                        .WithMany("Versions")
                        .HasForeignKey("SeatMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_versions_seat_maps_seat_map_id");

                    b.Navigation("SeatMap");
                });

            modelBuilder.Entity("Eventiq.SeatService.Domain.Entity.SeatObject", b =>
                {
                    b.HasOne("Eventiq.SeatService.Domain.Entity.SeatMap", "SeatMap")
                        .WithMany("Objects")
                        .HasForeignKey("SeatMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_objects_seat_maps_seat_map_id");

                    b.Navigation("SeatMap");
                });

            modelBuilder.Entity("Eventiq.SeatService.Domain.Entity.SeatMap", b =>
                {
                    b.Navigation("Objects");

                    b.Navigation("Seats");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
