// <auto-generated />
using System;
using Eventiq.SeatService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Eventiq.SeatService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SeatDbContext))]
    partial class SeatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Eventiq.SeatService.Domain.Entity.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomProperties")
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_properties");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid?>("LegendId")
                        .HasColumnType("uuid")
                        .HasColumnName("legend_id");

                    b.Property<string>("Position")
                        .HasColumnType("jsonb")
                        .HasColumnName("position");

                    b.Property<Guid>("RowId")
                        .HasColumnType("uuid")
                        .HasColumnName("row_id");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("integer")
                        .HasColumnName("seat_number");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seat_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_seats");

                    b.HasIndex("RowId")
                        .HasDatabaseName("ix_seats_row_id");

                    b.ToTable("seats", (string)null);
                });

            modelBuilder.Entity("Eventiq.SeatService.Domain.Entity.SeatMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanvasSettings")
                        .HasColumnType("jsonb")
                        .HasColumnName("canvas_settings");

                    b.Property<Guid>("ChartId")
                        .HasColumnType("uuid")
                        .HasColumnName("chart_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_seat_maps");

                    b.HasIndex("ChartId")
                        .IsUnique()
                        .HasDatabaseName("ix_seat_maps_chart_id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_seat_maps_event_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_seat_maps_organization_id");

                    b.ToTable("seat_maps", (string)null);
                });

            modelBuilder.Entity("Eventiq.SeatService.Domain.Entity.SeatMapVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeDescription")
                        .HasColumnType("text")
                        .HasColumnName("change_description");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("SeatMapId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_map_id");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_versions");

                    b.HasIndex("SeatMapId")
                        .HasDatabaseName("ix_versions_seat_map_id");

                    b.ToTable("versions", (string)null);
                });

            modelBuilder.Entity("Eventiq.SeatService.Domain.Entity.SeatObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Geometry")
                        .HasColumnType("jsonb")
                        .HasColumnName("geometry");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_type");

                    b.Property<Guid>("SeatMapId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_map_id");

                    b.Property<string>("Style")
                        .HasColumnType("jsonb")
                        .HasColumnName("style");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("ZIndex")
                        .HasColumnType("integer")
                        .HasColumnName("z_index");

                    b.HasKey("Id")
                        .HasName("pk_objects");

                    b.HasIndex("SeatMapId")
                        .HasDatabaseName("ix_objects_seat_map_id");

                    b.ToTable("objects", (string)null);
                });

            modelBuilder.Entity("Eventiq.SeatService.Domain.Entity.SeatRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Curve")
                        .HasColumnType("jsonb")
                        .HasColumnName("curve");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("row_number");

                    b.Property<int>("SeatSpacing")
                        .HasColumnType("integer")
                        .HasColumnName("seat_spacing");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_rows");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("ix_rows_section_id");

                    b.ToTable("rows", (string)null);
                });

            modelBuilder.Entity("Eventiq.SeatService.Domain.Entity.SeatSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Geometry")
                        .HasColumnType("jsonb")
                        .HasColumnName("geometry");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid?>("LegendId")
                        .HasColumnType("uuid")
                        .HasColumnName("legend_id");

                    b.Property<Guid>("SeatMapId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_map_id");

                    b.Property<string>("SectionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section_type");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Style")
                        .HasColumnType("jsonb")
                        .HasColumnName("style");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sections");

                    b.HasIndex("SeatMapId")
                        .HasDatabaseName("ix_sections_seat_map_id");

                    b.ToTable("sections", (string)null);
                });

            modelBuilder.Entity("Eventiq.SeatService.Domain.Entity.Seat", b =>
                {
                    b.HasOne("Eventiq.SeatService.Domain.Entity.SeatRow", "Row")
                        .WithMany("Seats")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seats_rows_row_id");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("Eventiq.SeatService.Domain.Entity.SeatMapVersion", b =>
                {
                    b.HasOne("Eventiq.SeatService.Domain.Entity.SeatMap", "SeatMap")
                        .WithMany("Versions")
                        .HasForeignKey("SeatMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_versions_seat_maps_seat_map_id");

                    b.Navigation("SeatMap");
                });

            modelBuilder.Entity("Eventiq.SeatService.Domain.Entity.SeatObject", b =>
                {
                    b.HasOne("Eventiq.SeatService.Domain.Entity.SeatMap", "SeatMap")
                        .WithMany("Objects")
                        .HasForeignKey("SeatMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_objects_seat_maps_seat_map_id");

                    b.Navigation("SeatMap");
                });

            modelBuilder.Entity("Eventiq.SeatService.Domain.Entity.SeatRow", b =>
                {
                    b.HasOne("Eventiq.SeatService.Domain.Entity.SeatSection", "Section")
                        .WithMany("Rows")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rows_sections_section_id");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Eventiq.SeatService.Domain.Entity.SeatSection", b =>
                {
                    b.HasOne("Eventiq.SeatService.Domain.Entity.SeatMap", "SeatMap")
                        .WithMany("Sections")
                        .HasForeignKey("SeatMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sections_seat_maps_seat_map_id");

                    b.Navigation("SeatMap");
                });

            modelBuilder.Entity("Eventiq.SeatService.Domain.Entity.SeatMap", b =>
                {
                    b.Navigation("Objects");

                    b.Navigation("Sections");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Eventiq.SeatService.Domain.Entity.SeatRow", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Eventiq.SeatService.Domain.Entity.SeatSection", b =>
                {
                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
